version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_local
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: localdb
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_local
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: yourpasswd
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  redis-server:
    image: redis:5.0.14
    container_name: redis_local
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  pgdata: null
  pgadmin-data: null
  redis-data: null
